// @todo: Add a file documentation header as explained in the specs ...

// @todo: If necessary, include q.h here ...

// @todo: Add necessary C standard library headers here ...

// @todo: Provide necessary definitions of functions
// that match corresponding declarations in q.h ...
